# ----
# Site

title: "Alma Dal Co School On Pattern Formation in Biological Systems Across Scales"
url: "https://almadalcoschool.github.io/" 
baseurl: #"/baseurl"
google_analytics_key: ""
google_maps_javascript_api_key:
disqus_shortname:

# Values for the jekyll-seo-tag gem (http://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
image: /images/home/paper_natEcoEvol2020.jpg
event_dates: "12th – 18th of September, 2027"
location: "San Servolo, Venice"
registration_status: "to come"
contact_name: "Silvia Casalini"
contact_email: "conferences@univiu.org"
contact_phone: "+39 041 2719 581"
contact_phone_link: "tel:+390412719581"
flyer_pdf: "POSTER.pdf"
description: ""
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: #Frisco Template
  links:
    #- http://github.com/CloudCannon/frisco-jekyll-template

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  attendees:
    _hide_content: true
  organizers:
    _hide_content: true

paginate: 10
paginate_path: "/blog/:num/"

jekyll-archives:
  enabled: ['categories']

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      _options:
        image:
          width: 2000
          height: 1322
          resize_style: cover
        content:
          width: 1500
          height: 2000
  -
    scope:
      path: "contact-success.html"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "pages"
    values:
      image:
        width: 2000
        height: 1322
        resize_style: cover
      bottom_image:
        width: 2000
        height: 1322
        resize_style: cover

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS

_comments:
  description: #Text shown when sharing on social media
  blurb: #Short bio or description of this person
